name: test-s390x-normal-2
on: [pull_request]

jobs:
  test:
    runs-on: [linux.s390x]
    timeout-minutes: 600
    strategy:
      fail-fast: false
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Prepare environment
      run: |
        virtualenv -p python3 --system-site-packages venv
        source venv/bin/activate
        pip install --upgrade setuptools
        pip install --upgrade pytest
        pip install --upgrade expecttest
        pip install --upgrade typing_extensions
        pip install --upgrade sympy
        pip install --upgrade hypothesis
        pip install --upgrade parameterized
    - name: Build project
      run: |
        source venv/bin/activate
        VERBOSE=1 BUILD_CAFFE2=1 BUILD_LIBTORCH_CPU_WITH_DEBUG=y USE_SYSTEM_GLOO=ON CMAKE_BUILD_TYPE=Debug python3 setup.py develop --user --cmake
    - name: Run python tests
      run: |
        source venv/bin/activate

        set +e

        failedlist=""

        for file in \
            test/distributed/_composable/test_compose.py \
            test/distributed/_composable/test_replicate.py \
            test/distributed/_tensor/test_redistribute.py \
            test/distributed/fsdp/test_fsdp_checkpoint.py \
            test/distributed/fsdp/test_fsdp_comm_hooks.py \
            test/distributed/fsdp/test_fsdp_flatten_params.py \
            test/distributed/fsdp/test_fsdp_ignored_modules.py \
            test/distributed/fsdp/test_fsdp_sharded_grad_scaler.py \
            test/distributed/fsdp/test_fsdp_unshard_params.py \
            test/distributed/fsdp/test_fsdp_use_orig_params.py \
            test/distributed/fsdp/test_wrap.py \
            test/distributed/optim/test_zero_redundancy_optimizer.py \
            test/distributed/tensor/parallel/test_tp_style.py \
            test/distributed/test_c10d_common.py \
            test/distributed/test_c10d_gloo.py \
            test/distributed/test_c10d_pypg.py \
            test/distributed/test_pg_wrapper.py \
            test/functorch/test_eager_transforms.py \
            test/inductor/test_minifier_isolate.py \
            test/jit/test_freezing.py \
            test/nn/test_convolution.py \
            test/nn/test_pooling.py \
            test/test_autograd.py \
            test/test_cpp_api_parity.py \
            test/test_cpp_extensions_jit.py \
            test/test_dispatch.py \
            test/test_expanded_weights.py \
            test/test_functionalization.py \
            test/test_fx_experimental.py \
            test/test_masked.py \
            test/test_multiprocessing.py \
            test/test_serialization.py \
            test/test_spectral_ops.py \
            test/test_tensor_creation_ops.py \
            test/test_tensorexpr.py \
            test/test_torch.py \
            test/test_transformers.py \
            test/test_utils.py \
            test/test_view_ops.py \
        ; do
            PYTHONPATH=$(pwd) pytest -v $file
            testresult=$?
            if [ $testresult -ne 0 ] ; then
                failedlist="$failedlist\n$file"
            fi
        done

        set -e

        if [ -n "$failedlist" ] ; then
            echo -e "Following tests failed:$failedlist"
            exit 1
        fi
