name: test-s390x-long-7
on: [pull_request]

jobs:
  test:
    runs-on: [linux.s390x]
    timeout-minutes: 1440
    strategy:
      fail-fast: false
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Prepare environment
      run: |
        virtualenv -p python3 --system-site-packages venv
        source venv/bin/activate
        pip install --upgrade setuptools
        pip install --upgrade pytest
        pip install --upgrade expecttest
        pip install --upgrade typing_extensions
        pip install --upgrade sympy
        pip install --upgrade hypothesis
        pip install --upgrade parameterized
    - name: Build project
      run: |
        source venv/bin/activate
        VERBOSE=1 BUILD_CAFFE2=1 BUILD_LIBTORCH_CPU_WITH_DEBUG=y USE_SYSTEM_GLOO=ON CMAKE_BUILD_TYPE=Debug python3 setup.py develop --user --cmake
    - name: Run python tests
      run: |
        source venv/bin/activate

        set +e

        failedlist=""

        for file in \
            test/test_jit_fuser_te.py \
            test/test_sparse.py \
        ; do
            PYTHONPATH=$(pwd) pytest -v $file
            testresult=$?
            if [ $testresult -ne 0 ] ; then
                failedlist="$failedlist\n$file"
            fi
        done

        set -e

        if [ -n "$failedlist" ] ; then
            echo -e "Following tests failed:$failedlist"
            exit 1
        fi
